#!/bin/sh

cd /app

echo 'Running migrations...'
python manage.py migrate


echo 'Collecting static files...'
python manage.py collectstatic --no-input

echo 'Running server...'
daphne config.asgi:application --bind 0.0.0.0 --port 8000
